const ActionType = {
    PENJUMLAHAN: 'PENJUMLAHAN',
    PENGURANGAN: 'PENGURANGAN',
    CHANGE_COUNT: 'CHANGE_COUNT',
    INITIAL_GET_DATA_MOVIE: 'INITIAL_GET_DATA_MOVIE',
    INITIAL_GET_GENRE_MOVIE:'INITIAL_GET_GENRE_MOVIE',
    GET_MOVIE_BY_NAME:'GET_MOVIE_BY_NAME'
}

export default ActionType